### ISSUE TITLE
Jars?

### ISSUE THREAD

**Issue by ElPresidentePro** [bensku/Skribble#1]
This project work?

**Comment by G1R-Productions** [comment]
No commits for 5 months. Not sure, I too would like to know.

**Comment by supertassu** [comment]
@bensku

**Comment by bensku** [comment]
I had to abandon this project for maintaining current Skript. Also, while this project features "good" bytecode generation, actual Skript parsing is... not good.

Skript's codebase is a mess, but it is also very big. I have decided that no point rewriting it, unless I'm paid to do so. This project is NOT functional.
